"""Rename AttendanceRecord to WakeSession and upgrade Ledger

Revision ID: 004a88078d1c
Revises: 2c23073b6592
Create Date: 2026-03-04 23:36:40.820859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004a88078d1c'
down_revision: Union[str, None] = '2c23073b6592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wake_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ALARM_SENT', 'OTP_ACTIVE', 'VERIFIED', 'FAILED', name='sessionstatus'), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('otp_expiry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['accountability_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wake_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wake_sessions_plan_id'), ['plan_id'], unique=False)

    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_otp_tokens_session_id', ['session_id'])
        batch_op.create_foreign_key('fk_otp_tokens_session_id_wake_sessions', 'wake_sessions', ['session_id'], ['id'])
        batch_op.drop_column('attendance_record_id')

    op.drop_table('attendance_records')

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('reference_id', sa.Integer(), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('DEPOSIT', 'PLAN_LOCK', 'PENALTY', 'REFUND', 'WITHDRAWAL', name='transactiontype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('DEPOSIT', 'PLAN_LOCK', 'PENALTY', 'REFUND', 'WITHDRAWAL', name='transactiontype'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('reference_id')
        batch_op.drop_column('balance_after')

    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_record_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'attendance_records', ['attendance_record_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('session_id')

    op.create_table('attendance_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('processed_flag', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['accountability_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_records_plan_id', ['plan_id'], unique=False)

    with op.batch_alter_table('wake_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wake_sessions_plan_id'))

    op.drop_table('wake_sessions')
    # ### end Alembic commands ###
