"""Add UserPreference and remove alarm schedule from Plan

Revision ID: 2c23073b6592
Revises: 744b8f7ed144
Create Date: 2026-03-04 22:49:16.212157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c23073b6592'
down_revision: Union[str, None] = '744b8f7ed144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('default_alarm_time', sa.Time(), nullable=True),
    sa.Column('weekend_alarm_time', sa.Time(), nullable=True),
    sa.Column('buffer_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('otp_window_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('accountability_plans', schema=None) as batch_op:
        batch_op.drop_column('alarm_time')
        batch_op.drop_column('otp_window_minutes')
        batch_op.drop_column('buffer_duration_minutes')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accountability_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buffer_duration_minutes', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('otp_window_minutes', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('alarm_time', sa.TIME(), nullable=False))

    op.drop_table('user_preferences')
    # ### end Alembic commands ###
