"""add scheduled_otp_drop_time

Revision ID: f79d674f36bd
Revises: 2cde6a0e4eb5
Create Date: 2026-08-18 15:23:31.247058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79d674f36bd'
down_revision: Union[str, None] = '2cde6a0e4eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wake_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_otp_drop_time', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wake_sessions', schema=None) as batch_op:
        batch_op.drop_column('scheduled_otp_drop_time')

    # ### end Alembic commands ###
